language: cpp
sudo: required
os:
- linux
addons:
addons:
  coverity_scan:
    project:
      name: "yigao/StaticNFrame"
      description: "Static Game Frame"
    notification_email: 445267987@qq.com
    build_command_prepend:
                   - cd product
                   - mkdir build
                   - cd build
                   - cmake -DCMAKE_BUILD_TYPE=Debug ../../  
    build_command: "make"
    branch_pattern: master
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake-data
    - cmake
    - automake

compiler:
- gcc
branches:
  only:
  - master
before_install:
- cd Tools
- tar -xvf automake-1.15.tar.gz
- cd automake-1.15
- chmod a+x ./configure
- ./configure
- make
- sudo make install
- cd ..
- rm -rf automake-1.15
- cd ..
- echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
install: ./build_dep.sh
script: 
   - make

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #    #   via the "travis encrypt" command using the project repo's public key
   - secure: "OByBxV9vA3AjzWyhfLagqsyVqrPQx5YQ4fSLdGKfwN7Yb8MN9LDlsxt790+tHT3NZMcPJKzp2h/XcV0Oa0j6tBcqZQONFdGaXM7VFBQ2aXuKBid3YGCVSNPztDhe3ffT0zPEwAyiI4LfouBcmtEQdoULlPhtcJbg+H9IICKlYfnb8ksYMpbpr+EpbK4Oye+aS5+aRnQrI3NSHsYgbRS3S36xoKeGZHaL22lc5aZhfwpis3UZauJWKOkfoIYYjv70LGdyDa8JXMm7piZCfNmndtpuwHAemojGtSESu7J8/233q1y/0iXdDFQnsppDa3fxnMXs/jB4RqtjVoqWrYj26IN85lMyhfBdBkCi8Jb8+a11yuKjhuodqmXSomzDOypWrHrJx7x/Ej7g0E31hIIRsNZG5IDOk99HWIEFhK6mnG/mzwqMU/99/x8ZaY8ugwJMy27TgbEOJUClpsYJp6C76KL2Y7asYVj3Tv01548KlZfPs08/o63Psdx9QYkGdcmumzIn04S7QTuMljwocnxrHGlpk7sOnyhbx2fFv1MWJ4Uc6gUZ5TXqfglKcmLbCu1ADssGDpV3WYNpcuobWFX5r3qUU4oIzSbLrH4yumFhnU+lsqjgbfEgeAXBqmQIr3YrQ7Ya4YS6ozeOzESABPHVhkbAlBfyu86Xq1CaeY/y8bU="
