language: cpp
sudo: required
os:
- linux
addons:
  sonarcloud:
      organization: "StaticNFrame"
      token:
           secure: "yzDa7TTCWijvwOayC6Ddj6pYBCBdaMTMuqF6RtusZQFLSmOCqmlxGzGbe6epRsu8g3+eKojUq3zzpyCnOQT6qGrDdCNlCuf7UYqwe+uCjBtUM9+DloeuA9I5V4wuQoCDdYZhucji9EfSjSS5Rz+BI6t6RqrXlf6PBy7vR0E721z83Bsls7inclCYYkOpX+oSLMKE/p7F6gQnD0vEQPvRevaVnkQsuBZKOikAgYmPF44bD3kwMV8leuA7jJyGkqPEA+RYD+2wMQPGEb3oN/u/ieSyXRx/3XdGOQ0fN0/7ILD7pmuesUmbF6gMLM9a/9HeKBLrP+s4T0HsL85tWF/9NHD6exQ40tSjmnCRQWU8Ls/164ikfM8mkOT9Ges4pAD4ILZxjl1jP8wFUl7u6fTmTOBd23QFku3i5OTOGeu59Wc8K+IZbnapoGy1vJ9ZX7rF2GoODkTW6dVwAV3JoyIU4ShDPu9UCLtHt/PG2Ac8duoJEBvrP2FbErKU9hvdUBuZVrKRxlwdlFuDd4tzghtXWyyG2xgGkOM9Y//0ORdhV07zIG3OyoG2e9ihpnH1xPeom1SBRAEzfN8t0pvarTTtpC5e6j5sNznnAXUl8wYNP3Pl2JnOTYuGcU3BCEXiCpbNZsi3elq9HS3FAYhJcvMzpCecMRJ8AZUH8zKCwNvARXA="
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake-data
    - cmake
    - automake

compiler:
- gcc
branches:
  only:
  - master
before_install:
- cd Tools
- tar -xvf automake-1.15.tar.gz
- cd automake-1.15
- chmod a+x ./configure
- ./configure
- make
- sudo make install
- cd ..
- rm -rf automake-1.15
- cd ..
install: ./build_dep.sh
script: 
   - cd Product
   - mkdir build
   - cd build
   - rm * -rf
   - cmake -DCMAKE_BUILD_TYPE=Debug ../../
   - make
   #- build-wrapper-linux-x86-64 --out-dir bw-output make all
   #- sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
