language: cpp
sudo: required
os:
  - linux
addons:
  ssh_known_hosts: 192.168.2.183 # 请替换成自己的服务器I
  apt:
    sources:
      #- ubuntu-toolchain-r-test
       - george-edison55-precise-backports
    packages:
      #- g++-4.9
       - cmake-data
       - cmake
compiler:
  - gcc
branches:
  only:
  - master
before_install:
    - openssl aes-256-cbc -K $encrypted_7eb6e0528deb_key -iv $encrypted_7eb6e0528deb_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - cd Tools
    - tar -xvf automake-1.15.tar.gz
    - cd automake-1.15
    - chmod a+x ./configure
    - ./configure 
    - make
    - sudo make install
    - cd ..
    - rm -rf automake-1.15
    - cd ..
install: ./build_dep.sh
script: ./build.sh
