language: cpp
sudo: required
os:
- linux
addons:
  sonarcloud:
       organization: "StaticNFrame"
          token:
            secure: "OSl/BVFjAozurwWeg0P2x2ToEXl/vTgtjEoRt9W6UWLo2KPOb1/p1Jn7fbm3MAxHadiT6d5Z3bcIegNmf5oah4EwpdNlSiqKHcrayHC33sCITpyW5eNnhaTgMMuT0iTDTjsiL18xHHJem1cOaaOOP2wr1FouTzOtzRQnbBmix3kOGEyGSPFE4UcTf31vxDzlaatWhpNJ1yYPjAsojMREumFXBFuRxCjGhe0xmw9PNO0iyWVMRk1CkDESLnuCdoi1kug6ZVWWYK6CMksdqPx60/sP2np3F65uSjHrrhWfG5iyBdirgY+OEiW8jeZ3A+2n0Sb6+1Z0QSs1DnpG6D0P2WNbMnfBLGnLkxNWiWlLrQKjS2nMkdZP0Mx83MIl7PqFNDK/ReA9xBXoC2B18QYMuPzTp8yJ22xwUrdrpPQwtTCwoej4J8Ec1GlMG0qtv/6HDo3mB+qrwP+ZThY570fLR/gm96kTKkLvOeQJl+BrUmY+/MfCdBW6M9BtuLxvGs6JzJAJAXFaSMKz11fFoLoJCm0/M93CECc3rUMk0ralaqUMLEIYkT4qxn/mAWgwpuQ4m1NMXP8xLB7W7VLWhYe+Wb2hsx6as1i8j3b6L1y84c8HfNH+DAyCa0hJRUoD/nGf6dj/wm42VPALg/+Zf7DxfUoKYGtceOk6KMqssuLEx1Q="

  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake-data
    - cmake
    - automake
compiler:
- gcc
branches:
  only:
  - master
before_install:
- cd Tools
- tar -xvf automake-1.15.tar.gz
- cd automake-1.15
- chmod a+x ./configure
- ./configure
- make
- sudo make install
- cd ..
- rm -rf automake-1.15
- cd ..

cache:
     directories:
       - '$HOME/.sonar/cache' 

install: ./build_dep.sh
script:
     - cd Product
     - mkdir build
     - cd build
     - cmake -DCMAKE_BUILD_TYPE=Debug ../../
     - build-wrapper-linux-x86-64 --out-dir bw-output make
     - sonar-scanner -Dsonar.organization=yigao-github
